
// ELEC2645 Unit 4 Assessment
// Editor: Aisya Afiqah Binti Mohd Fairoz Akasyah
// Game Title: Chick Knight
// ===========================
// A classic a 2D arcade survival game
//
// KEY CONCEPTS:
// - Game objects (Character, Coins, Ghost, Bullet, Flame) has their own data and mechanics
// - Created collision system based on circle's radius
// - Update/Render separation: game logic updates happen separately from drawing
//
// Controls:
// 1) Joystick (BTN3):
// - Start game in the beginning
// - Move character in all directions
// - Restart game from Level 1 when pressed after win / lose game
// 2) Push Button (BTN2):
// - Change character state to dashing mode (speed up movement)
// 3) Push Button (BTN4):
// - Pause and resume game
//
// Architecture:
// - Character: Main engine to control the character movement and states
// - Coins: Handles coins spawning and drawing with position, rendering and collision 
// - Ghost and Bullet: Handles ghosts and bullets spawning and drawing with position, movement, rendering and collision 
// - Flame: Handles flame spawning and drawing with position, rendering and collision 
// - Level: Handles amount of ghosts, coins and flame appearing per level
// - State: Update and render each game state

#include "Game_3.h"
#include "InputHandler.h"
#include "Menu.h"

// STM32 HAL headers (auto-generated by STM32CubeMX)
#include "main.h"
#include "stm32l4xx_hal.h"
#include "tim.h"       // Timer 2 for PWM buzzer control
#include "usart.h"     // For serial output
#include "gpio.h"      // GPIO control
#include "adc.h"       // ADC for joystick input
#include "rng.h"       // RNG for randomized ball reset

// AUTO-GENERATED STM32 FUNCTION PROTOTYPES - DO NOT EDIT
void SystemClock_Config(void);
void PeriphCommonClock_Config(void);

#include "Buzzer.h"     // Buzzer library
#include "PWM.h"        // PWM control of the LED 
#include "LCD.h"        // For LCD demonstration 
#include "Joystick.h"   // Include the Joystick driver functions
#include "Level.h"      // To customize each level
#include "Coins.h"      // Coins object with its system related to game sprite
#include "Ghost.h"      // Ghost object with its system related to game sprite
#include "Flame.h"       // Flame object with its system related to game sprite
#include "Character.h"  // Character (player) object with FSM for game sprite
#include "State.h"      // Manages game update and rendering

#include <stdint.h>
#include <stdio.h>
#include <math.h>

extern ST7789V2_cfg_t cfg0;
extern Buzzer_cfg_t buzzer_cfg;     // Buzzer control
extern PWM_cfg_t pwm_cfg;           // LED control
extern PWM_cfg_t pwm_cfg_2;  
extern Joystick_cfg_t joystick_cfg; // Joystick control

// ===== CHARACTER FSM VARIABLES =====
// Global character object
Character_t game_character;

// Initial game state before enter game playing mode
GameState_t game_state = GAME_START_PAGE; 

// Initial level state when enter enter game playing mode
LevelState_t level_state = LEVEL1; 


// ===== FUNCTION PROTOTYPES =====
void Game3_Update(Joystick_t *joystick_data);

// ===== Main Function =====

/**
  * @brief  The application entry point - Character FSM Demo
  * @retval int
  */
MenuState Game3_Run (void)
{
    /* MCU Configuration */
    HAL_Init();
    SystemClock_Config();
    PeriphCommonClock_Config();

    /* Initialize peripherals */
    MX_GPIO_Init();
    MX_USART2_UART_Init();
    MX_ADC1_Init();  // Initialize ADC for joystick
    
    // Initialize LCD first (this sets up GPIOB pins)
    LCD_init(&cfg0);

    // Initialize TIM4 AFTER LCD to avoid GPIO conflict on PB6
    MX_TIM4_Init();

    // Initialize Buzzer
    MX_TIM2_Init(); 
    buzzer_init(&buzzer_cfg);
  
    // Initialize Joystick
    Joystick_Init(&joystick_cfg);
    
    // Select LCD colour palette
    LCD_Set_Palette(PALETTE_AISYA);

    // Initialize Character
    Character_Init(&game_character);
    
    // Initialize PWM for red LED control
    PWM_Init(&pwm_cfg);
    PWM_SetFreq(&pwm_cfg, 1000);
    PWM_SetDuty(&pwm_cfg, 0);

    // Initialize PWM for yellow LED control
    PWM_Init(&pwm_cfg_2);
    PWM_SetDuty(&pwm_cfg_2, 0);

    // Initialize buttons
    Input_Init();
    
    // Ensure LD2 on PA5 starts OFF
    HAL_GPIO_WritePin(GPIOA, GPIO_PIN_5, GPIO_PIN_RESET);

    // Clear screen
    LCD_Fill_Buffer(0);   // 0 is stored as black in LCD.h
    LCD_Refresh(&cfg0);

    // Opening page with animation 
    uint32_t start_time = HAL_GetTick();          // Start opening page timer
    while (HAL_GetTick() - start_time < 4000) {   // Runs for 4 seconds
        opening_page();
    }

    HAL_Delay(500);   // Delay 500ms

    MenuState exit_state = MENU_STATE_HOME;

    // Joystick data structure to hold readings
    Joystick_t joystick_data;

    // Initialize seed for rand() function
    // Generate different sequence of the random number
    srand(HAL_GetTick());

    while (1)
    {
        // ===== CHICK KNIGHT MAIN LOOP =====

        // Read joystick input
        Joystick_Read(&joystick_cfg, &joystick_data);

        // Read buttons
        Input_Read();

        // Turn on LD2 on PA5
        HAL_GPIO_WritePin(GPIOA, GPIO_PIN_5, GPIO_PIN_SET);

        if (current_input.btn1_pressed) {
            exit_state = MENU_STATE_HOME;
            break;  // Exit game loop
        }

        Game3_Update(&joystick_data);

        HAL_Delay(30);  // only delay for non-playing states

    }

    return exit_state;
}
